#!/usr/bin/bash
#
#
#
#Colors                                                                 R='\033[1;31m'
G='\033[1;32m'                                                          Y='\033[1;33m'
B='\033[1;34m'                                                          M='\033[1;35m'                                                          C='\033[1;36m'                                                          W='\033[0m'
cd $HOME
echo $(clear)
function reiniciar {
	echo $(clear)
	HT
}
function banner {
	
printf '
_   _ ____  _       ____    _  _____ ___  ____
| | | |  _ \| |     |  _ \  / \|_   _/ _ \/ ___|
| | | | |_) | |     | | | |/ _ \ | || | | \___ \
| |_| |  _ <| |___  | |_| / ___ \| || |_| |___) |
 \___/|_| \_\_____| |____/_/   \_\_| \___/|____/
 ____ ___ ____      _  _____  _     __        _______ ____
|  _ \_ _|  _ \    / \|_   _|/ \    \ \      / / ____| __ )
| |_) | || |_) |  / _ \ | | / _ \    \ \ /\ / /|  _| |  _ \
|  __/| ||  _ <  / ___ \| |/ ___ \    \ V  V / | |___| |_) |
|_|  |___|_| \_\/_/   \_\_/_/   \_\    \_/\_/  |_____|____/

By LX MAS HERRAMIENTAS EN git clone http://github.com/LX772/FastTools.gi
t
'
}
echo
setterm -foreground yellow
banner
echo
setterm -foreground green
printf "
1) BUSCAR HOST (sin datos recomendado)

2) CHECK PUERTOS

3) BUSCAR IP EN LOS HOST

4) GUARDAR LOS HOST

5) VER LOS HOST GUARDADOS

6) INFO OF SCRIPT AUTHOR

00) SALIR
"
echo
read -p "Choose an Option >> " opt
case $opt in
	1)
		cd $HOME
		echo $(clear)
		setterm -foreground red
		banner
		setterm -foreground cyan
		echo
		echo
		read -p " HOST/IP
INTRODUCE EL URL (ejemplo' www.goole.com o google.com)

INTRODUCE EL HOST: " H
		echo
		bash .host/.s $H
		echo
		printf " PRESIONE ENTER PARA VOLVER"
		read enter
		reiniciar
		;;
	2)
		cd $HOME
		echo $(clear)
		setterm -foreground yellow
		banner
		setterm -foreground green
		echo
		echo
		read -p" INTRODUCE EL HOST/IP,

ES NECESARIO UN .com o IP PARA PREFERENCIA

IP/HOST: " I
echo
		nmap $I
		echo
		printf " ENTER PARA VOLVER"
		read enter
		reiniciar
		;;
	3)
		cd $HOME
		echo $(clear)
		setterm -foreground cyan
		banner
		setterm -foreground blue
		echo
		echo
		read -p " INTRODUCE EL HOST

PARA ENCONTRAR EL IP ES NECESARIO UN .com,.net,org.do etc

PARA TERMINAL VOL- + C

HOST: " O
echo
ping $O
echo
read -p " VOLVER AL MENU"
reiniciar
;;
4)
	cd $HOME
	echo $(clear)
	setterm -foreground blue
	banner
	setterm -foreground red yellow
	echo
	echo
	printf " GUARDA TUS HOST
Y PARA SALIR INTRODUCE
VOLUMEN ABAJO MAS TECLA C, VOL- + C

INSERTA LOS HOST COPIADOS
: "
cat>.host/.guardados.txt
echo
printf " VOLVER AL MENU"
read enter
reiniciar
;;
5)
	cd $HOME
	echo $(clear)
	setterm -foreground orange
	banner
	setterm -foreground purple
	echo
	echo
	sleep 5
	for i in  / - \ - \ - / - \ - / - \ - / - \ - / - \ -; do
		printf "$(clear) $Y [$G!$Y] $C ESPERA POR FAVOR. . . .$i\n"                                                                    
		sleep 1
	done
	sleep 5
	cd host
	cat .guardados.txt
	echo
	printf " VOLVER AL MENU"
	read enter
	reiniciar
	;;
6)
	echo $(clear)
	setterm -foreground red
	banner
	setterm -foreground cyan
	echo
	echo
	echo "
Author  : LX
Code    : bash                                                         
Version : 1.5 ( Beta )                                                                  "                                                      
printf "$G please send message for errors to Luisencarnacion772@gmail.com or search in telegram https://t.me/Minattto"
echo
printf $Y'                                                             
1) MESSAGE GMAIL                                                                                                                               
2) MESSAGE TELEGRAM                                                                                                                            
3) VOLVER AL MENU PRINCIPAL                                             '                                                                      
echo                                                                   
read -p " Choose an Option >> " b                                      
case $b in
	1)
               termux-open  https://accounts.google.com/Logout?service=mail&continue=https://mail.google.com/mail&hl=es-419
	       reiniciar
	       ;;
	2)
		termux-open https://t.me/Minattto
                reiniciar
                ;;
	3)
		reiniciar
		;;
esac
;;
00)
	echo $(exit)
	;;
esac
